"use client";
import { useRef, useState, type PointerEvent } from "react";
export function LightBulb({ dark, onToggle }: { dark: boolean; onToggle: () => void }) {
  const [pulling, setPulling] = useState(false); const [cordY, setCordY] = useState(0); const startY = useRef(0); const triggered = useRef(false);
  const down = (event: PointerEvent<SVGElement>) => { event.preventDefault(); setPulling(true); triggered.current = false; startY.current = event.clientY; event.currentTarget.setPointerCapture(event.pointerId); };
  const move = (event: PointerEvent<SVGElement>) => { if (!pulling) return; const distance = Math.max(0, Math.min(40, event.clientY - startY.current)); setCordY(distance); if (distance >= 32 && !triggered.current) { triggered.current = true; onToggle(); } };
  const up = () => { setPulling(false); setCordY(0); };
  return <button onClick={onToggle} aria-label={dark ? "Switch to light mode" : "Switch to dark mode"} className="flex flex-col items-center border-0 bg-transparent p-0"><svg width="32" height="44" viewBox="0 0 32 44" fill="none"><>{!dark && <circle cx="16" cy="14" r="13" fill="rgba(37,99,235,.08)" />}</><path d="M10 14a6 6 0 1 1 12 0c0 3-1.5 5-3 6.5V22h-6v-1.5C11.5 19 10 17 10 14z" stroke="var(--text)" strokeWidth="1.2" fill={dark ? "none" : "rgba(37,99,235,.12)"} /><rect x="13" y="22" width="6" height="2" rx="1" stroke="var(--text)" strokeWidth="1.2" /><rect x="13.5" y="24" width="5" height="1.5" rx=".75" stroke="var(--text)" /><>{!dark && <><line x1="16" y1="2" x2="16" y2="5" stroke="var(--accent)" strokeWidth="1.2" /><line x1="7" y1="5" x2="9" y2="7" stroke="var(--accent)" strokeWidth="1.2" /><line x1="25" y1="5" x2="23" y2="7" stroke="var(--accent)" strokeWidth="1.2" /></>}</><line x1="16" y1="25.5" x2="16" y2={32 + cordY} stroke="var(--text-faint)" strokeWidth="1" onPointerDown={down} onPointerMove={move} onPointerUp={up} className={pulling ? "cursor-grabbing" : "cursor-grab transition-all duration-300"} /><circle cx="16" cy={33 + cordY} r="1.5" fill="var(--text-faint)" onPointerDown={down} onPointerMove={move} onPointerUp={up} className="cursor-grab" /></svg></button>;
}
